server:
  port: 8080
spring:
  application:
    name: ehotel-service
  datasource:
    url: jdbc:postgresql://ehotel.czkxh7ra9ucu.us-east-2.rds.amazonaws.com/appdb
    username: postgres
    password: rootehotelapp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQL81Dialect
      hibernate:
        default_schema: ehotel
    database: POSTGRESQL
## Application Configuration Properties
application:
  jwt:
    secretKey: 12345678901234567890123456789012
    tokenExpirationAfterDays: 7
    refreshTokenExpirationAfterDays: 30
    tokenPrefix: "Bearer "
    accessHeader: access_token
    refreshHeader: refresh_token
    issuer: ehotelservices
    audience: ehotelfrontend







